# Generated by Django 3.0.6 on 2020-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0002_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
