# Generated by Django 3.0.6 on 2020-06-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0003_place_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='activity',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
